name: barber_english
description: "Aprende inglés para barberos - Barber English"
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  audioplayers: ^6.1.0
  shared_preferences: ^2.5.5
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: 6.4.1
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mascota.png
    - assets/pose1.png
    - assets/pose2.png
    - assets/pose3.png
    - assets/pose4.png
    - assets/pose5.png
    - assets/pose6.png
