// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrfkDWx1-8ov5y_naYUyNQkUIioeeooRI',
    appId: '1:625038868457:web:b8365e77cf504e48ff1578',
    messagingSenderId: '625038868457',
    projectId: 'barber-english',
    authDomain: 'barber-english.firebaseapp.com',
    storageBucket: 'barber-english.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI3YFqRL-2TsyLEMrkh6vuoZeBo1K9bF8',
    appId: '1:625038868457:android:61ced8eb21bcdbbaff1578',
    messagingSenderId: '625038868457',
    projectId: 'barber-english',
    storageBucket: 'barber-english.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALyqaL347v8WMxFeZ-brA4sEvapTLNaLo',
    appId: '1:625038868457:ios:8e8a228944fcf5efff1578',
    messagingSenderId: '625038868457',
    projectId: 'barber-english',
    storageBucket: 'barber-english.firebasestorage.app',
    iosBundleId: 'com.example.barberEnglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALyqaL347v8WMxFeZ-brA4sEvapTLNaLo',
    appId: '1:625038868457:ios:8e8a228944fcf5efff1578',
    messagingSenderId: '625038868457',
    projectId: 'barber-english',
    storageBucket: 'barber-english.firebasestorage.app',
    iosBundleId: 'com.example.barberEnglish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrfkDWx1-8ov5y_naYUyNQkUIioeeooRI',
    appId: '1:625038868457:web:f79643bf060d609cff1578',
    messagingSenderId: '625038868457',
    projectId: 'barber-english',
    authDomain: 'barber-english.firebaseapp.com',
    storageBucket: 'barber-english.firebasestorage.app',
  );
}
